name: Build and deploy Node.js app to Azure Web App - docshare
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
 
    steps:
      - uses: actions/checkout@v4
 
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
 
      - name: Install dependencies
        run: npm install
 
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .
 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
 
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
 
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1B096F4BA9D74E749FD7DAC2C8C5B151 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_21CED9CF50FC47A4BB8CB3BC7E566050 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D7879ECC269B4DFCBA14F427EF9700E9 }}
 
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'docshare'
          slot-name: 'Production'
          package: .
 
